version: "3.9"

services:
  database:
    image: postgres
    container_name: database_desafio
    restart: always
    ports:
      - 5433:5433
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=bankdb
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: dbapp
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
